DROP DATABASE IF EXISTS visflow;
CREATE DATABASE visflow;
USE visflow;

GRANT ALL PRIVILEGES ON visflow.* TO visflow@localhost;
DROP USER visflow@localhost;
CREATE USER visflow@localhost IDENTIFIED BY 'visflow';
GRANT ALL PRIVILEGES ON visflow.* TO visflow@localhost;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS data;

CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  password CHAR(64) NOT NULL,
  email VARCHAR(256) NOT NULL,
  register_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE data (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(256) NOT NULL,
  file_name VARCHAR(256) NOT NULL,
  file_path VARCHAR(512) NOT NULL,
  upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  size INT UNSIGNED NOT NULL,
  public BOOL DEFAULT false,
  CONSTRAINT FOREIGN KEY (user_id)
    REFERENCES visflow.user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE auth (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  session_id CHAR(64) NOT NULL,
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NOT NULL,
  CONSTRAINT FOREIGN KEY (user_id)
    REFERENCES visflow.user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE diagram (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(256) NOT NULL,
  file_path VARCHAR(512) NOT NULL,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  public BOOL DEFAULT false,
  CONSTRAINT FOREIGN KEY (user_id)
    REFERENCES visflow.user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO user (username, password, email) VALUES
  ('visflow', 'ec975f0ba679cebcfabb0b023893850202ac0f5a9533a25a3fc5e6c2f0fe1cab', 'visflow.nyu@gmail.com'),
  ('demo', '2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea', 'visflow.nyu@gmail.com');
