# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dataflow_ext_pb2 as dataflow__ext__pb2


class DataflowExtStub(object):
  """Optional dataflow service, through which a TA2 system can expose the
  internals of computations outlining a machine learning pipeline.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DescribeDataflow = channel.unary_unary(
        '/DataflowExt/DescribeDataflow',
        request_serializer=dataflow__ext__pb2.PipelineReference.SerializeToString,
        response_deserializer=dataflow__ext__pb2.DataflowDescription.FromString,
        )
    self.GetDataflowResults = channel.unary_stream(
        '/DataflowExt/GetDataflowResults',
        request_serializer=dataflow__ext__pb2.PipelineReference.SerializeToString,
        response_deserializer=dataflow__ext__pb2.ModuleResult.FromString,
        )


class DataflowExtServicer(object):
  """Optional dataflow service, through which a TA2 system can expose the
  internals of computations outlining a machine learning pipeline.
  """

  def DescribeDataflow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDataflowResults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataflowExtServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DescribeDataflow': grpc.unary_unary_rpc_method_handler(
          servicer.DescribeDataflow,
          request_deserializer=dataflow__ext__pb2.PipelineReference.FromString,
          response_serializer=dataflow__ext__pb2.DataflowDescription.SerializeToString,
      ),
      'GetDataflowResults': grpc.unary_stream_rpc_method_handler(
          servicer.GetDataflowResults,
          request_deserializer=dataflow__ext__pb2.PipelineReference.FromString,
          response_serializer=dataflow__ext__pb2.ModuleResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DataflowExt', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
